In the directory: /jukebox/LightSheetData/rat-brody/processed/201910_tracing/clearmap/z265/ClearMapCluster 
As the user: pnilsadmin 
on host: redshirt-n20 
Cpus_allowed_list:	0-6,16-22
Array Allocation Number: 18739718
Array Index: 2
['run_clearmap_cluster.py', '3', '2']
2
setting elastixlib path as /jukebox/pkgs/ELASTIX/4.8/bin, ***note this is a hack and may fail***
Elastix sucessfully initialized from path: /jukebox/pkgs/ELASTIX/4.8
list index out of range
Traceback (most recent call last):
  File "run_clearmap_cluster.py", line 116, in <module>
    alignment_operations(jobid, **params)
  File "/mnt/bucket/PNI-centers/LightSheetData/rat-brody/processed/201910_tracing/clearmap/z265/ClearMapCluster/ClearMap/cluster/par_tools.py", line 75, in alignment_operations
    return resultDirectory
UnboundLocalError: local variable 'resultDirectory' referenced before assignment
