In the directory: /jukebox/LightSheetData/rat-brody/processed/201910_tracing/clearmap/z265/ClearMapCluster 
As the user: pnilsadmin 
on host: spock7-c0-12 
Cpus_allowed_list:	13
Array Allocation Number: 18739717
Array Index: 3
['run_clearmap_cluster.py', '2', '3']
3
setting elastixlib path as /jukebox/pkgs/ELASTIX/4.8/bin, ***note this is a hack and may fail***
Elastix sucessfully initialized from path: /jukebox/pkgs/ELASTIX/4.8
Traceback (most recent call last):
  File "/jukebox/pkgs/ANACONDAPY/5.3.1/lib/python3.7/site-packages/pyximport/pyximport.py", line 215, in load_module
    inplace=build_inplace, language_level=language_level)
  File "/jukebox/pkgs/ANACONDAPY/5.3.1/lib/python3.7/site-packages/pyximport/pyximport.py", line 191, in build_module
    reload_support=pyxargs.reload_support)
  File "/jukebox/pkgs/ANACONDAPY/5.3.1/lib/python3.7/site-packages/pyximport/pyxbuild.py", line 102, in pyx_to_dll
    dist.run_commands()
  File "/jukebox/pkgs/ANACONDAPY/5.3.1/lib/python3.7/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/jukebox/pkgs/ANACONDAPY/5.3.1/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/jukebox/pkgs/ANACONDAPY/5.3.1/lib/python3.7/site-packages/Cython/Distutils/old_build_ext.py", line 186, in run
    _build_ext.build_ext.run(self)
  File "/jukebox/pkgs/ANACONDAPY/5.3.1/lib/python3.7/distutils/command/build_ext.py", line 339, in run
    self.build_extensions()
  File "/jukebox/pkgs/ANACONDAPY/5.3.1/lib/python3.7/site-packages/Cython/Distutils/old_build_ext.py", line 193, in build_extensions
    ext.sources = self.cython_sources(ext.sources, ext)
  File "/jukebox/pkgs/ANACONDAPY/5.3.1/lib/python3.7/site-packages/Cython/Distutils/old_build_ext.py", line 346, in cython_sources
    full_module_name=module_name)
  File "/jukebox/pkgs/ANACONDAPY/5.3.1/lib/python3.7/site-packages/Cython/Compiler/Main.py", line 700, in compile
    return compile_single(source, options, full_module_name)
  File "/jukebox/pkgs/ANACONDAPY/5.3.1/lib/python3.7/site-packages/Cython/Compiler/Main.py", line 649, in compile_single
    return run_pipeline(source, options, full_module_name)
  File "/jukebox/pkgs/ANACONDAPY/5.3.1/lib/python3.7/site-packages/Cython/Compiler/Main.py", line 499, in run_pipeline
    err, enddata = Pipeline.run_pipeline(pipeline, source)
  File "/jukebox/pkgs/ANACONDAPY/5.3.1/lib/python3.7/site-packages/Cython/Compiler/Pipeline.py", line 354, in run_pipeline
    data = run(phase, data)
  File "/jukebox/pkgs/ANACONDAPY/5.3.1/lib/python3.7/site-packages/Cython/Compiler/Pipeline.py", line 334, in run
    return phase(data)
  File "/jukebox/pkgs/ANACONDAPY/5.3.1/lib/python3.7/site-packages/Cython/Compiler/Pipeline.py", line 52, in generate_pyx_code_stage
    module_node.process_implementation(options, result)
  File "/jukebox/pkgs/ANACONDAPY/5.3.1/lib/python3.7/site-packages/Cython/Compiler/ModuleNode.py", line 142, in process_implementation
    self.generate_c_code(env, options, result)
  File "/jukebox/pkgs/ANACONDAPY/5.3.1/lib/python3.7/site-packages/Cython/Compiler/ModuleNode.py", line 400, in generate_c_code
    f = open_new_file(result.c_file)
  File "/jukebox/pkgs/ANACONDAPY/5.3.1/lib/python3.7/site-packages/Cython/Utils.py", line 57, in open_new_file
    os.unlink(path)
FileNotFoundError: [Errno 2] No such file or directory: '/usr/people/pnilsadmin/.pyxbld/temp.linux-x86_64-3.7/pyrex/ClearMap/Analysis/VoxelizationCode.c'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "run_clearmap_cluster.py", line 107, in <module>
    from ClearMap.cluster.par_tools import resampling_operations
  File "/mnt/bucket/PNI-centers/LightSheetData/rat-brody/processed/201910_tracing/clearmap/z265/ClearMapCluster/ClearMap/cluster/par_tools.py", line 14, in <module>
    from ClearMap.ImageProcessing.CellDetection import detectCells
  File "/mnt/bucket/PNI-centers/LightSheetData/rat-brody/processed/201910_tracing/clearmap/z265/ClearMapCluster/ClearMap/ImageProcessing/CellDetection.py", line 38, in <module>
    import ClearMap.ImageProcessing.SpotDetection
  File "/mnt/bucket/PNI-centers/LightSheetData/rat-brody/processed/201910_tracing/clearmap/z265/ClearMapCluster/ClearMap/ImageProcessing/SpotDetection.py", line 52, in <module>
    from ClearMap.ImageProcessing.IlluminationCorrection import correctIllumination
  File "/mnt/bucket/PNI-centers/LightSheetData/rat-brody/processed/201910_tracing/clearmap/z265/ClearMapCluster/ClearMap/ImageProcessing/IlluminationCorrection.py", line 40, in <module>
    from ClearMap.Visualization.Plot import plotTiling
  File "/mnt/bucket/PNI-centers/LightSheetData/rat-brody/processed/201910_tracing/clearmap/z265/ClearMapCluster/ClearMap/Visualization/Plot.py", line 24, in <module>
    import ClearMap.Analysis.Voxelization as vox
  File "/mnt/bucket/PNI-centers/LightSheetData/rat-brody/processed/201910_tracing/clearmap/z265/ClearMapCluster/ClearMap/Analysis/Voxelization.py", line 15, in <module>
    import ClearMap.Analysis.VoxelizationCode as vox
  File "/jukebox/pkgs/ANACONDAPY/5.3.1/lib/python3.7/site-packages/pyximport/pyximport.py", line 458, in load_module
    language_level=self.language_level)
  File "/jukebox/pkgs/ANACONDAPY/5.3.1/lib/python3.7/site-packages/pyximport/pyximport.py", line 231, in load_module
    raise exc.with_traceback(tb)
  File "/jukebox/pkgs/ANACONDAPY/5.3.1/lib/python3.7/site-packages/pyximport/pyximport.py", line 215, in load_module
    inplace=build_inplace, language_level=language_level)
  File "/jukebox/pkgs/ANACONDAPY/5.3.1/lib/python3.7/site-packages/pyximport/pyximport.py", line 191, in build_module
    reload_support=pyxargs.reload_support)
  File "/jukebox/pkgs/ANACONDAPY/5.3.1/lib/python3.7/site-packages/pyximport/pyxbuild.py", line 102, in pyx_to_dll
    dist.run_commands()
  File "/jukebox/pkgs/ANACONDAPY/5.3.1/lib/python3.7/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/jukebox/pkgs/ANACONDAPY/5.3.1/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/jukebox/pkgs/ANACONDAPY/5.3.1/lib/python3.7/site-packages/Cython/Distutils/old_build_ext.py", line 186, in run
    _build_ext.build_ext.run(self)
  File "/jukebox/pkgs/ANACONDAPY/5.3.1/lib/python3.7/distutils/command/build_ext.py", line 339, in run
    self.build_extensions()
  File "/jukebox/pkgs/ANACONDAPY/5.3.1/lib/python3.7/site-packages/Cython/Distutils/old_build_ext.py", line 193, in build_extensions
    ext.sources = self.cython_sources(ext.sources, ext)
  File "/jukebox/pkgs/ANACONDAPY/5.3.1/lib/python3.7/site-packages/Cython/Distutils/old_build_ext.py", line 346, in cython_sources
    full_module_name=module_name)
  File "/jukebox/pkgs/ANACONDAPY/5.3.1/lib/python3.7/site-packages/Cython/Compiler/Main.py", line 700, in compile
    return compile_single(source, options, full_module_name)
  File "/jukebox/pkgs/ANACONDAPY/5.3.1/lib/python3.7/site-packages/Cython/Compiler/Main.py", line 649, in compile_single
    return run_pipeline(source, options, full_module_name)
  File "/jukebox/pkgs/ANACONDAPY/5.3.1/lib/python3.7/site-packages/Cython/Compiler/Main.py", line 499, in run_pipeline
    err, enddata = Pipeline.run_pipeline(pipeline, source)
  File "/jukebox/pkgs/ANACONDAPY/5.3.1/lib/python3.7/site-packages/Cython/Compiler/Pipeline.py", line 354, in run_pipeline
    data = run(phase, data)
  File "/jukebox/pkgs/ANACONDAPY/5.3.1/lib/python3.7/site-packages/Cython/Compiler/Pipeline.py", line 334, in run
    return phase(data)
  File "/jukebox/pkgs/ANACONDAPY/5.3.1/lib/python3.7/site-packages/Cython/Compiler/Pipeline.py", line 52, in generate_pyx_code_stage
    module_node.process_implementation(options, result)
  File "/jukebox/pkgs/ANACONDAPY/5.3.1/lib/python3.7/site-packages/Cython/Compiler/ModuleNode.py", line 142, in process_implementation
    self.generate_c_code(env, options, result)
  File "/jukebox/pkgs/ANACONDAPY/5.3.1/lib/python3.7/site-packages/Cython/Compiler/ModuleNode.py", line 400, in generate_c_code
    f = open_new_file(result.c_file)
  File "/jukebox/pkgs/ANACONDAPY/5.3.1/lib/python3.7/site-packages/Cython/Utils.py", line 57, in open_new_file
    os.unlink(path)
ImportError: Building module ClearMap.Analysis.VoxelizationCode failed: ["FileNotFoundError: [Errno 2] No such file or directory: '/usr/people/pnilsadmin/.pyxbld/temp.linux-x86_64-3.7/pyrex/ClearMap/Analysis/VoxelizationCode.c'\n"]
