step 1 launching with inputs scope and file as follows:
/scratch/ejdennis/cm2_brains/X078/642
smartspim
QStandardPaths: XDG_RUNTIME_DIR points to non-existing path '/run/user/2333', please create it with 0700 permissions.
libEGL warning: DRI2: failed to create any config
libEGL warning: DRI2: failed to create any config
libEGL warning: DRI2: failed to create any config
libEGL warning: DRI2: failed to create any config
/usr/people/ejdennis/.conda/envs/cm2/lib/python3.6/site-packages/vispy/visuals/line/line.py:395: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  ('color', np.float32, 4)])
/usr/people/ejdennis/.conda/envs/cm2/lib/python3.6/site-packages/vispy/visuals/line/arrow.py:57: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  ('linewidth', np.float32, 1)
/usr/people/ejdennis/.conda/envs/cm2/lib/python3.6/site-packages/vispy/visuals/isocurve.py:22: UserWarning: VisPy is not yet compatible with matplotlib 2.2+
  warnings.warn("VisPy is not yet compatible with matplotlib 2.2+")
about to import workspace
Traceback (most recent call last):
  File "/usr/people/ejdennis/.conda/envs/cm2/lib/python3.6/site-packages/pyximport/pyximport.py", line 216, in load_module
    mod = imp.load_dynamic(name, so_path)
  File "/usr/people/ejdennis/.conda/envs/cm2/lib/python3.6/imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: /usr/people/ejdennis/.pyxbld/lib.linux-x86_64-3.6/DevolvePointListCode.cpython-36m-x86_64-linux-gnu.so.reload1: file too short

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "cell_detect.py", line 13, in <module>
    import ClearMap.ImageProcessing.Experts.Cells as cells
  File "/scratch/ejdennis/rat_BrainPipe/ClearMap2/ClearMap/ImageProcessing/Experts/Cells.py", line 40, in <module>
    import ClearMap.Analysis.Measurements.ShapeDetection as sd
  File "/scratch/ejdennis/rat_BrainPipe/ClearMap2/ClearMap/Analysis/Measurements/ShapeDetection.py", line 35, in <module>
    import ClearMap.Analysis.Measurements.Voxelization as vox
  File "/scratch/ejdennis/rat_BrainPipe/ClearMap2/ClearMap/Analysis/Measurements/Voxelization.py", line 18, in <module>
    import ClearMap.ParallelProcessing.DataProcessing.DevolvePointList as dpl
  File "/scratch/ejdennis/rat_BrainPipe/ClearMap2/ClearMap/ParallelProcessing/DataProcessing/DevolvePointList.py", line 29, in <module>
    import ClearMap.ParallelProcessing.DataProcessing.DevolvePointListCode as code
  File "/usr/people/ejdennis/.conda/envs/cm2/lib/python3.6/site-packages/pyximport/pyximport.py", line 462, in load_module
    language_level=self.language_level)
  File "/usr/people/ejdennis/.conda/envs/cm2/lib/python3.6/site-packages/pyximport/pyximport.py", line 231, in load_module
    raise exc.with_traceback(tb)
  File "/usr/people/ejdennis/.conda/envs/cm2/lib/python3.6/site-packages/pyximport/pyximport.py", line 216, in load_module
    mod = imp.load_dynamic(name, so_path)
  File "/usr/people/ejdennis/.conda/envs/cm2/lib/python3.6/imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: Building module ClearMap.ParallelProcessing.DataProcessing.DevolvePointListCode failed: ['ImportError: /usr/people/ejdennis/.pyxbld/lib.linux-x86_64-3.6/DevolvePointListCode.cpython-36m-x86_64-linux-gnu.so.reload1: file too short\n']
